apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  # storageClassName: jenkins-pv
  # accessModes:
  # - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  # hostPath:
  #   path: /data/jenkins-volume/
  nfs:
    path: /srv/nfs/kubedata
    server: controlplane01

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  # storageClassName: jenkins-pv
  volumeName: jenkins-pv

# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: jenkins-pv
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer

