---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-server
  namespace: jenkins
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  selector:
    app: jenkins-server
  ports:
    - port: 8080
      targetPort: 8080