services:
  jenkins:
    image: ${JENKINS_IMAGE:-jenkins/jenkins:latest}
    container_name: jenkins
    ports:
      - "${JENKINS_PORT:-8080}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    networks:
      - jenkins
    volumes:
      - "${JENKINS_VOLUME:-/var/jenkins_home}:/var/jenkins_home"
      - //var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=${JENKINS_JAVA_OPTS:--Djenkins.install.runSetupWizard=false}
      - DOCKER_HOST=${DOCKER_HOST:-tcp://host.docker.internal:2375}

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "${SONARQUBE_PORT:-9000}:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://${SONARQUBE_DB_URL:-postgres:5432}/sonarqube
      SONAR_JDBC_USERNAME: ${SONARQUBE_DB_USER:-sonarqube}
      SONAR_JDBC_PASSWORD: ${SONARQUBE_DB_PASSWORD:-sonarqube}
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - postgres
    networks:
      - jenkins

  postgres:
    image: postgres:17.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${SONARQUBE_DB_USER:-sonarqube}
      POSTGRES_PASSWORD: ${SONARQUBE_DB_PASSWORD:-sonarqube}
      POSTGRES_DB: ${SONARQUBE_DB_NAME:-sonarqube}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgresql:/var/lib/postgresql
    networks:
      - jenkins
    ports:
      - "5432:5432"

  jenkins-ssh-agent:
    image: jenkins/ssh-agent:latest
    container_name: jenkins-ssh-agent
    ports:
      - "${SSH_AGENT_PORT:-22}:22"
    networks:
      - jenkins
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSH_PUBLIC_KEY}
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins

volumes:
  jenkins-data:
    external: true
  postgres_data:
  postgresql:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:

networks:
  jenkins:
    external: true
