- name: Update and upgrade system packages
  hosts: all
  become: true
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Update and upgrade system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install common dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - unzip
        - curl
        - openjdk-17-jre
        - s3fs
    - name: Create credentials file for S3 access
      ansible.builtin.copy:
        dest: /etc/passwd-s3fs
        content: "{{ aws_access_key_id }}:{{ aws_secret_access_key }}"
        owner: root
        group: root
        mode: '0600'


- name: Configure SonarQube
  hosts: sonarqube
  become: true
  vars_files:
    - vars/main.yaml
  vars:
    app_name: "sonarqube"
  roles:
    - sonarqube

- name: Configure Jenkins
  hosts: jenkins
  become: true
  vars_files:
    - vars/main.yaml
  vars:
    app_name: "jenkins"
  roles:
    - jenkins
